/* GENERATED by tools/mktext.py from ../text/strings.txt -- do not edit. */

#ifndef _STRINGS_H_
#define _STRINGS_H_

extern const char TXT_TITLE[12];   /* 'ZX TEMPLATE' */
extern const char TXT_LBL_MACHINE[10];   /* 'MACHINE :' */
extern const char TXT_LBL_KEMPSTON[10];   /* 'KEMPSTON:' */
extern const char TXT_LBL_VSYNC[10];   /* 'VSYNC   :' */
extern const char TXT_MACHINE_128K[11];   /* '128K CLASS' */
extern const char TXT_MACHINE_48K[4];   /* '48K' */
extern const char TXT_YES[4];   /* 'YES' */
extern const char TXT_NO[3];   /* 'NO' */
extern const char TXT_VSYNC_BUS_48K[20];   /* 'FLOATING BUS 0X40FF' */
extern const char TXT_VSYNC_BUS_128K[20];   /* 'FLOATING BUS 0X0FFD' */
extern const char TXT_VSYNC_HALT[14];   /* 'HALT FALLBACK' */
extern const char TXT_NOTE_1[27];   /* 'BORDER STEPS ONCE A FRAME.' */
extern const char TXT_NOTE_2[26];   /* 'A STEADY EDGE MEANS IT IS' */
extern const char TXT_NOTE_3[23];   /* 'IN STEP WITH THE BEAM.' */

#endif /* _STRINGS_H_ */
