#!/usr/bin/env python3
"""Lift the ZX0 blobs out of the C program and into a standalone binary.

The blobs are read once, at boot, to decompress into the tile buffers.
Kept as C arrays they sit in RODATA below 0xC000 and spend the scarcest
thing this program has: the 16 KB code budget.  They do not need to be
there.

So two files are generated from the same data:

  src/assets_low.asm       the bytes, assembled STANDALONE at 0x6000 and
                           shipped as its own CODE block by mktap.py.
                           Never linked into the C program, so it costs
                           the code budget nothing.

  src/assets_low_syms.asm  `defc _name = addr` for each blob, PUBLIC and
                           linked in.  Resolves the `extern const uint8_t
                           name[]` the generated headers already declare,
                           at zero bytes -- the same trick that removes
                           the unused 4x8 font.

Nothing in the C source changes except dropping the `#define
X_DEFINE_DATA` lines that used to claim ownership of a copy.

0x6000-0x7FFF is contended, which costs nothing here: the blobs are read
once during boot, not per frame.
"""

import glob
import os
import re
import sys

ORG = 0x6000
LIMIT = 0x7FA0          # the stack lives just below 0x8000

# 0x6000-0x7FA0 is free ONLY because include/memmap.h keeps the hand-placed
# buffers at 0xDB00.  Move MEM_VBUF back down and this block is loaded
# underneath the renderer's scratch, which shows up as corrupt level data
# several levels in, not as a load failure.  The guard below is the check.


def blobs():
    """Every ZX0 array a generated header can define, with its bytes."""
    out = []
    # EVERY generated header, so a new asset needs no change here: the
    # generators emit its bytes behind a *_ZX0_INLINE guard nothing
    # defines, and this picks them up automatically.
    for path in sorted(glob.glob('include/*.h')):
        src = open(path).read()
        for m in re.finditer(
                r'const uint8_t (\w+_zx0)\[(\d+)\] = \{(.*?)\};', src, re.S):
            name, n, body = m.group(1), int(m.group(2)), m.group(3)
            # `_bank_` blobs go to a RAM bank, which only a 128K has, and
            # are packaged separately.  Sweeping them in here would put
            # them in the block every machine loads -- which is the cost
            # banking exists to avoid.
            if '_bank_' in name:
                continue
            data = [int(v, 0) for v in re.findall(r'0x[0-9A-Fa-f]+', body)]
            if len(data) != n:
                sys.exit('mkassets: %s declares %d bytes but lists %d'
                         % (name, n, len(data)))
            out.append((name, data, path))
    return out


def check_no_overlap(lo, hi):
    """Refuse to build a block that memmap.h has buffers sitting on."""
    src = open('include/memmap.h').read()
    m = re.search(r'#define MEM_VBUF\s+(0x[0-9A-Fa-f]+)', src)
    if not m:
        sys.exit('mkassets: cannot find MEM_VBUF in include/memmap.h')
    vbuf = int(m.group(1), 16)
    if vbuf < hi:
        sys.exit('mkassets: assets 0x%04X-0x%04X collide with MEM_VBUF at '
                 '0x%04X -- the renderer would overwrite them, and it shows '
                 'up as corrupt level data, not a load failure' % (lo, hi, vbuf))


def main():
    found = blobs()
    if not found:
        sys.exit('mkassets: no *_zx0 arrays found -- did the generators run?')

    total = sum(len(d) for _, d, _ in found)
    check_no_overlap(ORG, ORG + total)
    if ORG + total > LIMIT:
        sys.exit('mkassets: %d bytes at 0x%04X would reach 0x%04X, past the '
                 'stack at 0x%04X' % (total, ORG, ORG + total, LIMIT))

    data_lines = ['; Generated by tools/mkassets.py -- do not edit.',
                  '; ZX0 asset blobs, assembled standalone and loaded as their',
                  '; own CODE block.  See the header of tools/mkassets.py.',
                  '',
                  '    org     0x%04X' % ORG, '']
    sym_lines = ['; Generated by tools/mkassets.py -- do not edit.',
                 '; Addresses only, no bytes: these resolve the extern',
                 '; declarations in the generated headers to the standalone',
                 '; blob loaded at 0x%04X, and cost nothing.' % ORG,
                 '',
                 '    MODULE  assets_low_syms', '']

    addr = ORG
    for name, data, path in found:
        data_lines.append('; %s -- %d bytes, from %s' % (name, len(data), path))
        data_lines.append('_%s:' % name)
        for i in range(0, len(data), 16):
            row = ', '.join('0x%02X' % b for b in data[i:i + 16])
            data_lines.append('    defb    ' + row)
        data_lines.append('')
        sym_lines.append('    PUBLIC  _%s' % name)
        sym_lines.append('    defc    _%s = 0x%04X' % (name, addr))
        addr += len(data)

    open('src/assets_low.asm', 'w').write('\n'.join(data_lines) + '\n')
    open('src/assets_low_syms.asm', 'w').write('\n'.join(sym_lines) + '\n')

    # Whatever goes below the program next starts here.  Emitted rather
    # than written down in two places: the blob total moves whenever an
    # asset is added, and src/logic_org.asm and the mktap --code flag both
    # need the same number.  Getting them out of step puts one block on
    # top of the other -- mktap now refuses that, but only after a build
    # has already been wasted.
    nxt = (addr + 0xFF) & ~0xFF         # round up, so the map reads clearly
    open('src/logic_org.asm', 'w').write(
        '; Generated by tools/mkassets.py -- do not edit.\n'
        ';\n'
        '; Puts logic.c in the contended window below the program.  It is\n'
        '; the right module for it: AI and pathfinding run once per turn,\n'
        '; not once per frame, so the ULA stealing a cycle from every fetch\n'
        '; costs nothing measurable -- the state walk is unchanged at ~19s.\n'
        '; Moving ALL code down here instead cost about 50%%.  The render\n'
        '; path stays at 0x8000 for that reason.\n'
        ';\n'
        '; 0x%04X is the first free byte after the asset blobs.\n'
        '    SECTION LOGIC\n'
        '    org     0x%04X\n' % (nxt, nxt))
    open('logic_org.addr', 'w').write('0x%04X\n' % nxt)

    print('mkassets: %d blobs, %d bytes at 0x%04X..0x%04X; next free 0x%04X '
          '(%d bytes to the stack)' % (len(found), total, ORG, addr, nxt,
                                       LIMIT - nxt))


main()
