#!/usr/bin/env python3
"""mktext.py — text/strings.txt -> include/strings.h + src/strings.c

Every string the player reads lives in ONE file, so adding or changing
wording is an edit to a text file rather than a hunt through three C
sources.  It also makes the set of strings countable, which is what any
later compression needs: see docs/PLAN.md § Text.

FORMAT

    # comments and blank lines are ignored
    ID = the text, up to the end of the line

The text is taken literally, INCLUDING trailing spaces, which several
strings rely on for padding.  Quote it if that makes the padding easier
to see:

    STATUS_BLANK = "-                     "

DEDUPLICATION is the point of doing this at all.  Two IDs with identical
text share one array, and the second becomes a #define of the first, so
the bytes appear once.  The C compiler does not reliably pool string
literals across translation sprites, and this project had 91 runs in the
binary for 82 distinct strings.

PACKING (--pack)

Two things, both invisible to callers because only text_expand() decodes:

  * a WORD DICTIONARY.  Repeated whole words become one byte each.
    Tokens live at 0x01-0x1F, which the 64-column font cannot print, so
    they cannot collide with text.  31 is the ceiling; the generator
    takes the most valuable and stops.
  * a HIGH-BIT TERMINATOR.  Bit 7 set marks the LAST byte of a string
    rather than spending a NUL on it.  A token can be last, so the two
    schemes share the byte: 0x81-0x9F is "last, and a token".

text_expand() also stops at a NUL, so a plain C string -- a terrain name,
anything not from this file -- passes through unchanged.  That is what
lets print_at() decode unconditionally instead of every caller choosing.

WHAT THIS DOES NOT DO

No ZX0.  Measured on this project's real corpus: ZX0 on the whole
block saves 378 bytes but needs a 913-byte buffer to unpack into, which
is most of the free data space; per-string or per-level compression is
WORSE than storing the text raw, because the redundancy is across strings
rather than within them.  A word dictionary and a high-bit terminator
together save about 195 bytes with a 32-byte buffer and keep random
access, and are the sensible next step if the space is needed.  All of
that is a change to this generator and to str_of(), not to any caller --
which is the reason for the indirection.
"""

import argparse
import os
import re
import sys

HEADER_WARNING = "/* GENERATED by tools/mktext.py from %s -- do not edit. */"


def parse(path):
    """[(id, text)] in file order, rejecting anything ambiguous."""
    out, seen = [], {}
    for n, line in enumerate(open(path), 1):
        line = line.rstrip("\n")
        if not line.strip() or line.lstrip().startswith("#"):
            continue
        if "=" not in line:
            sys.exit("%s:%d: no '=' in %r" % (path, n, line))
        ident, text = line.split("=", 1)
        ident = ident.strip()
        text = text[1:] if text.startswith(" ") else text

        # An optional pair of quotes makes trailing spaces visible; they
        # are not part of the text.
        if len(text) >= 2 and text[0] == '"' and text[-1] == '"':
            text = text[1:-1]

        if not re.fullmatch(r"[A-Z][A-Z0-9_]*", ident):
            sys.exit("%s:%d: %r is not an UPPER_SNAKE id" % (path, n, ident))
        if ident in seen:
            sys.exit("%s:%d: %s already defined on line %d"
                     % (path, n, ident, seen[ident]))
        if any(c in text for c in '"\\'):
            sys.exit("%s:%d: %s contains a quote or backslash, which the "
                     "generator does not escape" % (path, n, ident))
        if not all(32 <= ord(c) < 127 for c in text):
            sys.exit("%s:%d: %s has a character the 64-column font cannot "
                     "print" % (path, n, ident))
        seen[ident] = n
        out.append((ident, text))
    return out


def build_dict(texts, limit=31):
    """The words worth a token, most valuable first.

       A word costs its own bytes plus a NUL in the dictionary, and saves
       len-1 bytes at every use.  Anything that does not clear that is
       left as literal text."""
    from collections import Counter
    counts = Counter()
    for t in texts:
        for w in re.findall(r"[A-Za-z0-9]{2,}", t):
            counts[w] += 1
    scored = []
    for w, n in counts.items():
        gain = (len(w) - 1) * n - (len(w) + 1)
        if gain > 0:
            scored.append((gain, w))
    scored.sort(reverse=True)
    return [w for _, w in scored[:limit]]


def pack(text, words):
    """text -> bytes, words as tokens, bit 7 marking the last byte."""
    out = bytearray()
    i = 0
    while i < len(text):
        for n, w in enumerate(words):
            if text.startswith(w, i):
                # only on a word boundary, or "SPACES" would tokenise
                after = i + len(w)
                before_ok = i == 0 or not text[i - 1].isalnum()
                after_ok = after >= len(text) or not text[after].isalnum()
                if before_ok and after_ok:
                    out.append(n + 1)
                    i = after
                    break
        else:
            out.append(ord(text[i]))
            i += 1
    if out:
        out[-1] |= 0x80
    else:
        # An empty string packs to nothing, and C rejects an empty
        # initialiser.  A lone NUL is the plain-string form, which
        # text_expand() stops on immediately -- so it decodes to "".
        out.append(0)
    return bytes(out)


def unpack(b, words):
    """The decoder, in Python, so the build can check itself."""
    out = []
    for x in b:
        last = x & 0x80
        x &= 0x7F
        if not x:
            break
        out.append(words[x - 1] if x < 0x20 else chr(x))
        if last:
            break
    return "".join(out)


def emit_zx0(args, items, uniq, aliases):
    """One ZX0 blob, unpacked once at boot.

       This beats the word dictionary for two reasons.  ZX0 finds
       repetition INSIDE words and across punctuation, not just whole
       words -- 628 bytes go to 356 against the dictionary's 500.  And
       the decompressor is dzx0, which the graphics and the music already
       link, so the decoder costs NOTHING; the dictionary needed 116
       bytes of bespoke expander, which at this many strings was more
       than it saved.

       The cost is a buffer holding every string at once.  That is
       affordable only because it goes ABOVE MEM_END, where a 128K's
       paging means code can never live and there was space going spare.

       TXT_FOO expands to a CONSTANT ADDRESS, not a lookup.  The pool
       lands at a fixed place and the offsets are known here, so
       `(const char *)(MEM_TEXTPOOL + 123)` is exactly as cheap at the
       call site as the plain array it replaces -- one `ld hl,nn`.

       The first attempt went through a str_of(n) function instead, and
       that was measurably wrong: the extra push/call/return cost about
       six bytes at each of 52 call sites, some 300 bytes, against 180
       saved.  The contended block overran by 15 bytes and the build
       stopped, which is the only reason it was noticed before shipping.
       An offset table is not needed either, so that is 92 bytes more."""
    import subprocess, tempfile

    pool = bytearray()
    offs = []
    for _, text in uniq:
        offs.append(len(pool))
        pool += text.encode("latin-1") + b"\x00"

    with tempfile.TemporaryDirectory() as t:
        raw = os.path.join(t, "pool.bin")
        z = os.path.join(t, "pool.zx0")
        rt = os.path.join(t, "pool.rt")
        open(raw, "wb").write(bytes(pool))
        subprocess.run([args.zx0, "-f", raw, z], check=True, capture_output=True)
        blob = open(z, "rb").read()

        # ROUND TRIP in the build.  This project has twice shipped data
        # that a compressor had quietly altered.
        subprocess.run([args.dzx0, z, rt], check=True, capture_output=True)
        if open(rt, "rb").read() != bytes(pool):
            sys.exit("mktext: the pool does not survive a ZX0 round trip")

    at = {ident: off for (ident, _), off in zip(uniq, offs)}
    rel = os.path.relpath(args.input, os.path.dirname(args.header) or ".")
    h = [HEADER_WARNING % rel, "",
         "#ifndef _STRINGS_H_", "#define _STRINGS_H_", "",
         "#include <stdint.h>", "",
         '#include "memmap.h"', "",
         "/* The pool is ZX0 in the program and unpacked to a FIXED address",
         "   at boot, so every string's address is known here.  TXT_* is a",
         "   constant, costing one `ld hl,nn` at the call site -- the same",
         "   as the plain array it replaced. */",
         "#define TEXT_COUNT      %d" % len(uniq),
         "#define TEXT_POOL_SIZE  %d" % len(pool), "",
         "void text_init(void);", ""]
    for ident, text in uniq:
        h.append("#define TXT_%-30s ((const char *)(MEM_TEXTPOOL + %d))   /* %r */"
                 % (ident, at[ident], text))
    if aliases:
        h += ["", "/* identical text, so one entry serves both */"]
        for ident, target in aliases:
            h.append("#define TXT_%-30s TXT_%s" % (ident, target))
    h += ["", "#endif /* _STRINGS_H_ */", ""]

    c = [HEADER_WARNING % os.path.relpath(args.input,
                                          os.path.dirname(args.source) or "."),
         "",
         "#include <stdint.h>", "",
         "/* %d bytes of text, ZX0 to %d." % (len(pool), len(blob)),
         "   Verified in the build to survive a round trip. */",
         "const uint8_t text_zx0[%d] = {" % len(blob)]
    for i in range(0, len(blob), 16):
        c.append("    " + ",".join("%d" % b for b in blob[i:i + 16]) + ",")
    c += ["};", "",
          "/* No offset table: the addresses are compile-time constants in",
          "   strings.h, so nothing needs to look one up. */", ""]

    open(args.header, "w").write("\n".join(h))
    open(args.source, "w").write("\n".join(c))
    print("mktext: %d strings, %d distinct  pool %d -> %d ZX0, round trip ok"
          % (len(items), len(uniq), len(pool), len(blob)))
    return 0


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("input")
    ap.add_argument("--header", required=True)
    ap.add_argument("--source", required=True)
    ap.add_argument("--pack", action="store_true",
                    help="word dictionary + high-bit terminator (superseded "
                         "by --zx0; kept because it needs no buffer)")
    ap.add_argument("--zx0", metavar="COMPRESSOR", default=None,
                    help="ZX0 the whole pool; unpacked once at boot into "
                         "MEM_TEXTPOOL by text_init()")
    ap.add_argument("--dzx0", default=os.path.expanduser("~/z88dk/bin/z88dk-dzx0"))
    ap.add_argument("--width", type=int, default=32,
                    help="the display is this many characters wide; longer "
                         "strings are a mistake, not a wrap")
    args = ap.parse_args()

    items = parse(args.input)
    if not items:
        sys.exit("mktext: %s defines nothing" % args.input)

    too_long = [(i, t) for i, t in items if len(t) > args.width]
    if too_long:
        for i, t in too_long:
            print("mktext: %s is %d characters, the screen is %d"
                  % (i, len(t), args.width), file=sys.stderr)
        sys.exit(1)

    # text -> the first id that carried it; the rest become #defines
    first, aliases, uniq = {}, [], []
    for ident, text in items:
        if text in first:
            aliases.append((ident, first[text]))
        else:
            first[text] = ident
            uniq.append((ident, text))

    words = build_dict([t for _, t in uniq]) if args.pack else []

    if args.zx0:
        return emit_zx0(args, items, uniq, aliases)

    rel = os.path.relpath(args.input, os.path.dirname(args.header) or ".")
    h = [HEADER_WARNING % rel, "",
         "#ifndef _STRINGS_H_", "#define _STRINGS_H_", ""]
    for ident, text in uniq:
        n = len(pack(text, words)) if args.pack else len(text) + 1
        h.append("extern const char TXT_%s[%d];   /* %r */" % (ident, n, text))
    if aliases:
        h += ["", "/* identical text, so one array serves both */"]
        for ident, target in aliases:
            h.append("#define TXT_%s TXT_%s" % (ident, target))
    h += ["", "#endif /* _STRINGS_H_ */", ""]

    raw_total = sum(len(t) + 1 for _, t in uniq)

    c = [HEADER_WARNING % os.path.relpath(args.input,
                                          os.path.dirname(args.source) or "."),
         ""]
    if args.pack:
        dict_bytes = sum(len(w) + 1 for w in words)
        c += ["/* The dictionary: NUL-separated, scanned rather than indexed.",
              "   %d words, %d bytes; an offset table would cost %d more and"
              % (len(words), dict_bytes, 2 * len(words)),
              "   save a scan nobody can see behind a screen write. */",
              # +1: the concatenated literals carry an implicit NUL of
              # their own after the last explicit one.
              "const char text_dict[%d] = " % (dict_bytes + 1)]
        c.append("    " + "\n    ".join(
            '"%s\\0"' % w for w in words) + ";")
        c.append("")
    else:
        c += ["/* Plain arrays, no offset table: at this size a uint16 index",
              "   would cost %d bytes and save nothing. */" % (2 * len(uniq)),
              ""]

    packed_total = 0
    for ident, text in uniq:
        if args.pack:
            b = pack(text, words)
            packed_total += len(b)
            c.append("const char TXT_%s[%d] = {%s};   /* %r */"
                     % (ident, len(b), ",".join("%d" % x for x in b), text))
        else:
            c.append('const char TXT_%s[%d] = "%s";' % (ident, len(text) + 1, text))
    c.append("")

    open(args.header, "w").write("\n".join(h))
    open(args.source, "w").write("\n".join(c))

    if args.pack:
        dict_bytes = sum(len(w) + 1 for w in words)
        print("mktext: %d strings, %d distinct  %d -> %d bytes packed "
              "+ %d dictionary = %d  (%+d)"
              % (len(items), len(uniq), raw_total, packed_total, dict_bytes,
                 packed_total + dict_bytes,
                 packed_total + dict_bytes - raw_total))
    else:
        print("mktext: %d strings, %d distinct, %d bytes (%d saved by sharing)"
              % (len(items), len(uniq), raw_total,
                 sum(len(t) + 1 for i, t in items) - raw_total))

    # ROUND TRIP: decode everything back and compare.  A packer that
    # silently drops a word is the failure this project has shipped twice.
    if args.pack:
        for ident, text in uniq:
            if unpack(pack(text, words), words) != text:
                sys.exit("mktext: %s does not survive a round trip" % ident)


if __name__ == "__main__":
    sys.exit(main())
