/* GENERATED by tools/mktext.py from ../text/strings.txt -- do not edit. */

/* Plain arrays, no offset table: at this size a uint16 index
   would cost 28 bytes and save nothing. */

const char TXT_TITLE[12] = "ZX TEMPLATE";
const char TXT_LBL_MACHINE[10] = "MACHINE :";
const char TXT_LBL_KEMPSTON[10] = "KEMPSTON:";
const char TXT_LBL_VSYNC[10] = "VSYNC   :";
const char TXT_MACHINE_128K[11] = "128K CLASS";
const char TXT_MACHINE_48K[4] = "48K";
const char TXT_YES[4] = "YES";
const char TXT_NO[3] = "NO";
const char TXT_VSYNC_BUS_48K[20] = "FLOATING BUS 0X40FF";
const char TXT_VSYNC_BUS_128K[20] = "FLOATING BUS 0X0FFD";
const char TXT_VSYNC_HALT[14] = "HALT FALLBACK";
const char TXT_NOTE_1[27] = "BORDER STEPS ONCE A FRAME.";
const char TXT_NOTE_2[26] = "A STEADY EDGE MEANS IT IS";
const char TXT_NOTE_3[23] = "IN STEP WITH THE BEAM.";
